### ISSUE TITLE
Check thread-safety of newly implemented classes

### ISSUE THREAD

**Issue by AgentTroll** [TridentSDK/Trident#67]
Please check or at least make a decent attempt at ensuring the classes that are used in a multithreaded context have the proper initialization safety and access safety for accessors that are given to plugins for modification.

**Comment by caojohnny** [comment]
UI elements probably need some sort of synchronization when sent or else 2 tablists or titles could be sent at once to the player.

With that said, are UI elements removed from the tablist when it is destroyed?
