### ISSUE TITLE
Minecraft's title resetting is mentally retarded

### ISSUE THREAD

**Issue by AgentTroll** [TridentSDK/Trident#75]
See TridentPlayer#resetTitle()

Titles cannot be fully reset, the subtitle is a remnant artifact even after using the PlayOutTitle#Reset packet. Therefore, 3 packets are sent instead, each to set all the fields to empty/default values.

**Comment by nickrobson** [comment]
Ref: https://github.com/TridentSDK/Trident/blob/revamp/src/main/java/net/tridentsdk/server/player/TridentPlayer.java#L416
